# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate mixture Sequential Probability Ratio Test in Cpp
#'
#' @param x,y Numeric vectors
#' @param sigma Population standard deviation
#' @param tau Mixture variance
#' @param theta Hypothesised difference between \code{x} and \code{y}
#' @param distribution The desired distribution.
#' @param alpha Significance level
#' @return The likelihood ratio
#' @export
NULL

testing <- function(x, y, sigma, tau, theta = 0, distribution = "normal") {
    .Call('_mixtureSPRT_testing', PACKAGE = 'mixtureSPRT', x, y, sigma, tau, theta, distribution)
}

